server:
  port: 8080
jwt:
  key: aaa
spring:
  application:
    admin: gateway
  cloud:
    gateway:
      default-filters:
        - LogFilter
      routes:
        - id: first-service
          uri: http://localhost:8081
          predicates:
            - Path=/first-service/**
          filters:
            - RewritePath=/first-service(?<segment>.*), /$\{segment}
        - id: second-service
          uri: http://localhost:8082
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service(?<segment>.*), /$\{segment}
