server:
  port: 8080
spring:
  application:
    admin: gateway
spring:
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081
          predicates:
            - Path=/first-service/**
          filters:
            - RewritePath=/first-service(?<segment>.*), /$\{segment}
            - CustomJWTFilter # service1 ? ???? ??
        - id: second-service
          uri: http://localhost:8082
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service(?<segment>.*), /$\{segment}
